### PR TITLE
Initial draft design to track ACR

### PR DESCRIPTION
**Pull request by jorgecotillo**
Initial design doc to allow tracking of ACR without enforcing it.

### CODE REVIEW

**Comment by bennage** [comment]
Instead of ACR, can we refer to this as a tracking id?
I think that "ACR" won't mean much to external partners, and positioning it as a tracking id allows for other use cases.
Thoughts?

**Comment by jceval** [comment]
> Instead of ACR, can we refer to this as a tracking id?
> I think that "ACR" won't mean much to external partners, and positioning it as a tracking id allows for other use cases.
> Thoughts?

It is referred to a 'usage attribution' in the documentation. https://docs.microsoft.com/en-us/azure/marketplace/azure-partner-customer-usage-attribution

**Comment by alguadam** [comment]
> > Instead of ACR, can we refer to this as a tracking id?
> > I think that "ACR" won't mean much to external partners, and positioning it as a tracking id allows for other use cases.
> > Thoughts?
> 
> It is referred to a 'usage attribution' in the documentation. https://docs.microsoft.com/en-us/azure/marketplace/azure-partner-customer-usage-attribution

I like the idea of being consistent with the documentation and use the term 'usage attribution'

**Comment by jorgecotillo** [comment]
changes made based on feedback, please review and let me know if is ok.

**Pull request merged**
